export const APP_STORE_METADATA = {
  name: 'QuipPix',
  subtitle: 'Photo to Art, Instantly',
  description:
    'Transform your photos into stunning art styles with QuipPix. Choose from 15 unique styles including caricatures, comic book, pop art, watercolor, oil painting, and more. Customize every detail with intuitive sliders, then share your creations with friends.',
  keywords: [
    'photo art',
    'caricature',
    'portrait',
    'AI art',
    'style transfer',
    'comic book',
    'pop art',
    'watercolor',
    'oil painting',
    'photo editor',
    'art filter',
    'photo to art',
    'cartoon',
    'illustration',
    'digital art',
  ],
  category: 'Photo & Video',
  secondaryCategory: 'Entertainment',
  contentRating: '4+',
  privacyUrl: 'https://quippix.app/privacy',
  termsUrl: 'https://quippix.app/terms',
  supportUrl: 'https://quippix.app/support',
  marketingUrl: 'https://quippix.app',
} as const;
