import { FastifyInstance, FastifyReply } from 'fastify';

const COMPANY = 'Motiontography';
const APP_NAME = 'QuipPix';
const PRIVACY_EMAIL = 'privacy@motiontography.com';
const LEGAL_EMAIL = 'legal@motiontography.com';
const EFFECTIVE_DATE = 'February 4, 2026';

function page(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — ${APP_NAME}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.7; color: #1d1d1f; background: #fff; padding: 2rem 1.5rem; max-width: 720px; margin: 0 auto; }
    h1 { font-size: 1.8rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1.2rem; margin-top: 2rem; margin-bottom: 0.5rem; }
    p, li { font-size: 1rem; margin-bottom: 0.75rem; }
    ul { padding-left: 1.5rem; }
    .date { color: #6e6e73; font-size: 0.9rem; margin-bottom: 2rem; }
    a { color: #0066cc; }
  </style>
</head>
<body>
${body}
</body>
</html>`;
}

const privacyHtml = page(
  'Privacy Policy',
  `
<h1>Privacy Policy</h1>
<p class="date">Effective date: ${EFFECTIVE_DATE}</p>

<p>${APP_NAME} is operated by ${COMPANY}. This policy explains how we handle your data when you use the ${APP_NAME} app.</p>

<h2>1. What We Collect</h2>
<p>The only personal data we process is the photo you choose to transform. We do not require an account, email address, name, or any other personal information.</p>

<h2>2. How We Use Your Photo</h2>
<p>Your photo is uploaded to our servers solely to generate the styled image you requested. It is sent to our image-processing provider (OpenAI) for transformation and is not used for any other purpose.</p>

<h2>3. EXIF Data</h2>
<p>All EXIF metadata (location, camera info, timestamps) is stripped from your photo before it leaves your device. We never see or store this metadata.</p>

<h2>4. Data Retention</h2>
<p>Uploaded photos and generated images are automatically deleted from our servers within 1 hour of processing. We do not keep copies.</p>

<h2>5. Third-Party Services</h2>
<ul>
  <li><strong>OpenAI</strong> — processes your photo to generate the styled image. Subject to <a href="https://openai.com/policies/privacy-policy">OpenAI's Privacy Policy</a>.</li>
  <li><strong>RevenueCat</strong> — manages in-app purchases using an anonymous device identifier. No personal data is shared. Subject to <a href="https://www.revenuecat.com/privacy">RevenueCat's Privacy Policy</a>.</li>
</ul>

<h2>6. Analytics &amp; Tracking</h2>
<p>We do not use analytics, advertising SDKs, or tracking of any kind.</p>

<h2>7. Accounts</h2>
<p>No account creation or login is required. There are no usernames, passwords, or profiles.</p>

<h2>8. Children's Privacy</h2>
<p>${APP_NAME} does not knowingly collect data from children. Because we collect no personal data, the app is suitable for users of all ages.</p>

<h2>9. Your Rights</h2>
<p>Since we do not store personal data beyond the temporary photo processing window, there is no persistent data to access, correct, or delete. If you have questions, contact us at <a href="mailto:${PRIVACY_EMAIL}">${PRIVACY_EMAIL}</a>.</p>

<h2>10. Changes to This Policy</h2>
<p>We may update this policy from time to time. The current version will always be available at this URL.</p>

<h2>11. Contact</h2>
<p>If you have questions about this privacy policy, contact us at <a href="mailto:${PRIVACY_EMAIL}">${PRIVACY_EMAIL}</a>.</p>
`,
);

const termsHtml = page(
  'Terms of Service',
  `
<h1>Terms of Service</h1>
<p class="date">Effective date: ${EFFECTIVE_DATE}</p>

<p>By using ${APP_NAME}, you agree to the following terms.</p>

<h2>1. The Service</h2>
<p>${APP_NAME} is a photo transformation app operated by ${COMPANY}. It allows you to apply AI-powered artistic styles to your photos.</p>

<h2>2. Free &amp; Pro Tiers</h2>
<p>${APP_NAME} offers a free tier with limited styles and daily generations, and an optional paid Pro tier. Pro is available as a monthly subscription, annual subscription, or one-time lifetime purchase. Subscription pricing and availability are shown in the app before purchase.</p>

<h2>3. Subscriptions</h2>
<p>Subscriptions are billed through Apple (App Store) or Google (Play Store). Payment is charged to your account at confirmation of purchase. Subscriptions auto-renew unless canceled at least 24 hours before the current period ends. Manage or cancel subscriptions through your device's store settings.</p>

<h2>4. Your Content</h2>
<p>You retain all rights to your original photos. Transformed images generated by ${APP_NAME} are yours to use, share, and modify without restriction.</p>

<h2>5. Acceptable Use</h2>
<p>You may not use ${APP_NAME} to generate content that is illegal, harmful, harassing, or sexually explicit. We reserve the right to refuse processing requests that violate this policy.</p>

<h2>6. Content Moderation</h2>
<p>We apply automated moderation to prompts and generated images. Requests that violate our content policy may be rejected.</p>

<h2>7. Disclaimer of Warranties</h2>
<p>The service is provided "as is" without warranty of any kind, express or implied. We do not guarantee uninterrupted availability or specific results.</p>

<h2>8. Limitation of Liability</h2>
<p>To the maximum extent permitted by law, ${COMPANY} shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app.</p>

<h2>9. Changes to These Terms</h2>
<p>We may update these terms from time to time. Continued use of the app constitutes acceptance of the updated terms.</p>

<h2>10. Contact</h2>
<p>If you have questions about these terms, contact us at <a href="mailto:${LEGAL_EMAIL}">${LEGAL_EMAIL}</a>.</p>
`,
);

export async function privacyRoutes(app: FastifyInstance): Promise<void> {
  app.get('/privacy', async (_request, reply: FastifyReply) => {
    reply.type('text/html').send(privacyHtml);
  });

  app.get('/terms', async (_request, reply: FastifyReply) => {
    reply.type('text/html').send(termsHtml);
  });
}
